STOP_DATASTREAM = '#o0'
START_DATASTREAM = '#o1'

GET_CALIBRATION_VALUES ='#p'

SET_BINARY_FORMAT = '#ob'
SET_TEXT_FORMAT = '#ot'
SET_TEXT_EXTENDED_FORMAT_NO_MAG = '#ox' # Use this one in the ROS driver WITHOUT magnetometer
SET_TEXT_EXTENDED_FORMAT_WITH_MAG = '#om' # Use this one in the ROS driver WITH magnetometer
SET_CALIBRATION_OUTPUT_MODE = '#oc'
NEXT_SENSOR_CALIBRATION = '#on'

LINE_START_NO_MAG = "#YPRAG="
LINE_START_WITH_MAG = "#YPRAGM="

ENABLE_ERROR_MESSAGE = '#oe1'
DISABLE_ERROR_MESSAGE = '#oe0'
OUTPUT_ERROR_COUNT = '#oec'
OUTPUT_MATH_ERROR_COUNT = '#oem'

SET_CALIB_ACC_X_MIN = '#caxm'
SET_CALIB_ACC_X_MAX = '#caxM'
SET_CALIB_ACC_Y_MIN = '#caym'
SET_CALIB_ACC_Y_MAX = '#cayM'
SET_CALIB_ACC_Z_MIN = '#cazm'
SET_CALIB_ACC_Z_MAX = '#cazM'

SET_MAG_X_MIN = '#cmxm'
SET_MAG_X_MAX = '#cmxM'
SET_MAG_Y_MIN = '#cmym'
SET_MAG_Y_MAX = '#cmyM'
SET_MAG_Z_MIN = '#cmzm'
SET_MAG_Z_MAX = '#cmzM'

SET_MAG_ELLIPSOID_CENTER_0 = '#ccx'
SET_MAG_ELLIPSOID_CENTER_1 = '#ccy'
SET_MAG_ELLIPSOID_CENTER_2 = '#ccz'
SET_MAG_ELLIPSOID_TRANSFORM_0_0 = '#ctxX'
SET_MAG_ELLIPSOID_TRANSFORM_0_1 = '#ctxY'
SET_MAG_ELLIPSOID_TRANSFORM_0_2 = '#ctxZ'
SET_MAG_ELLIPSOID_TRANSFORM_1_0 = '#ctyX'
SET_MAG_ELLIPSOID_TRANSFORM_1_1 = '#ctyY'
SET_MAG_ELLIPSOID_TRANSFORM_1_2 = '#ctyZ'
SET_MAG_ELLIPSOID_TRANSFORM_2_0 = '#ctzX'
SET_MAG_ELLIPSOID_TRANSFORM_2_1 = '#ctzY'
SET_MAG_ELLIPSOID_TRANSFORM_2_2 = '#ctzZ'

SET_GYRO_AVERAGE_OFFSET_X = '#cgx'
SET_GYRO_AVERAGE_OFFSET_Y = '#cgy'
SET_GYRO_AVERAGE_OFFSET_Z = '#cgz'
